// <auto-generated />
namespace CustomAuthentication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedCommentnavigationToPost_Account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCommentnavigationToPost_Account));
        
        string IMigrationMetadata.Id
        {
            get { return "201602041801587_addedCommentnavigationToPost_Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
